### PR TITLE
feat: core optimized CSS font file

### PR DESCRIPTION
**Pull request by coryrylan**
## Feature:
Support a optimized CSS file that loads only necessary fonts that are easily consumed by CDNs and bundler tools. For `@clr/core` to load Clarity City fonts it needs the paths defined within the `@clr/city` package. When they are defined within the `@clr/core` package the CSS bundler support was not great. Some tools understood the `node_module` resolution into a different package while others did not.

- include only font weights used within the Clarity Design System
- inline imports for request chain reduction from CSS imports
- font swap for more resilient loading and render performance of web components
- single file for easier CDNs consumption
   ex: `<link href="https://unpkg.com/@clr/city/css/core.min.css" rel="stylesheet">`
- include inlined imports for better bundler support

Example of request chain performance issues when loading via CDN
Screen Shot 2019-12-06 at 11 32 17 PM

### CODE REVIEW

**Comment by coryrylan** [comment]
If this is ok, I'd like to ship it under a 1.1.0 release so we can continue testing Core.

**Comment by mathisscott** [comment]
> If this is ok, I'd like to ship it under a 1.1.0 release so we can continue testing Core.

I don't know if I understand what you mean here? A 1.1.0 Clarity release?

**Comment by coryrylan** [comment]
Clarity City is on a different version than the rest of the packages https://github.com/vmware/clarity-city/blob/master/package.json#L3

**Comment by gnomeontherun** [comment]
My main question is if we can come up with a better name for this `core` file, because that is very specific to our implementation and I want to keep this more agnostic to Clarity's implementation.

**Pull request merged**
